/* Generated By:JavaCC: Do not edit this line. AuthenticateIDPasswordTacticGrammaireConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AuthenticateIDPasswordTacticGrammaireConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LITERAL = 5;
  /** RegularExpression Id. */
  int OBJ = 6;
  /** RegularExpression Id. */
  int Method_Signature = 7;
  /** RegularExpression Id. */
  int OBJJ = 8;
  /** RegularExpression Id. */
  int CALLER = 9;
  /** RegularExpression Id. */
  int CALLEE = 10;
  /** RegularExpression Id. */
  int METHOD = 11;
  /** RegularExpression Id. */
  int COMMA = 12;
  /** RegularExpression Id. */
  int COMMAP = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<LITERAL>",
    "<OBJ>",
    "<Method_Signature>",
    "<OBJJ>",
    "\"CALLER:\"",
    "\"CALLEE:\"",
    "\"METHOD:\"",
    "\",\"",
    "\";\"",
  };

}
